export const GOOGLE_SIGIN = "GOOGLE_SIGIN"
export const SIGN_IN = "SIGN_IN"
export const NEW_STAFF = "NEW_STAFF"
export const SHOW_EMPLOYEE = "SHOW_EMPLOYEE"
export const LOG_OUT = "LOG_OUT"
export const SHOW_PROJECT = "SHOW_PROJECT"
export const PROJECT_DETAILS = "PROJECT_DETAILS"